apiVersion: batch/v1
kind: Job
metadata:
  name: k6-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/test.js"]
        env:
          - name: VUS
            value: "{{ .Values.vus }}"
          - name: DURATION
            value: "{{ .Values.duration }}"
          - name: TARGET_URL
            value: "{{ .Values.targetUrl }}"
        volumeMounts:
          - name: k6
            mountPath: /scripts
      volumes:
        - name: k6
          configMap:
            name: k6