apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
  - name: trace-analyzer
    image: ubuntu:latest
    # Comando per mantenere il pod in esecuzione
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: traces-storage
      mountPath: "/data" # Montiamo il volume in /data
  volumes:
  - name: traces-storage
    persistentVolumeClaim:
      claimName: {{ .Values.pvc.existingClaim }} # Usa il valore da values.yaml
